export const levelData = [

    {level: 1, numberOfCards: 100, symbols: ["あ", "い", "あ", "う", "あ", "え", "お"], target: {symbol: "あ", sound: "a"}},
    {level: 2, numberOfCards: 100, symbols: ["あ", "い", "う", "い", "え", "い", "お"], target: {symbol: "い", sound: "i"}},
    {level: 3, numberOfCards: 100, symbols: ["あ", "い", "う", "え", "う", "お", "う"], target: {symbol: "う", sound: "u"}},
    {level: 4, numberOfCards: 100, symbols: ["あ", "え", "い", "う", "え", "お", "え"], target: {symbol: "え", sound: "e"}},
    {level: 5, numberOfCards: 100, symbols: ["あ", "お", "い", "お", "う", "え", "お"], target: {symbol: "お", sound: "o"}},
    {level: 6, numberOfCards: 100, symbols: ["か", "き", "か", "く", "け", "こ", "か"], target: {symbol: "か", sound: "ka"}},
    {level: 7, numberOfCards: 100, symbols: ["か", "き", "く","き", "け", "こ", "き"], target: {symbol: "き", sound: "ki"}},
    {level: 8, numberOfCards: 100, symbols: ["か", "く", "き", "く", "け", "く", "こ"], target: {symbol: "く", sound: "ku"}},
    {level: 9, numberOfCards: 100, symbols: ["か", "け", "き", "く", "け", "こ", "け"], target: {symbol: "け", sound: "ke"}},
    {level: 10, numberOfCards: 100, symbols: ["か", "こ", "き", "こ", "く", "け", "こ"], target: {symbol: "こ", sound: "ko"}},
    {level: 11, numberOfCards: 100, symbols: ["さ", "し", "す", "さ", "せ", "そ", "さ"], target: {symbol: "さ", sound: "sa"}},
    {level: 12, numberOfCards: 100, symbols: ["さ", "し", "す", "せ", "し", "そ", "し"], target: {symbol: "し", sound: "shi"}},
    {level: 13, numberOfCards: 100, symbols: ["さ", "す", "し", "す", "せ", "す", "そ"], target: {symbol: "す", sound: "su"}},
    {level: 14, numberOfCards: 100, symbols: ["さ", "せ", "し", "せ", "す", "せ", "そ"], target: {symbol: "せ", sound: "se"}},
    {level: 15, numberOfCards: 100, symbols: ["さ", "そ", "し", "そ", "す", "せ", "そ"], target: {symbol: "そ", sound: "so"}},
    {level: 16, numberOfCards: 100, symbols: ["た", "ち","た", "つ", "て", "と", "た"], target: {symbol: "た", sound: "ta"}},
    {level: 17, numberOfCards: 100, symbols: ["た", "ち", "つ", "ち", "て", "と", "ち"], target: {symbol: "ち", sound: "chi"}},
    {level: 18, numberOfCards: 100, symbols: ["た", "つ", "ち", "つ", "て", "と", "つ"], target: {symbol: "つ", sound: "tsu"}},
    {level: 19, numberOfCards: 100, symbols: ["た", "て", "ち", "て", "と", "つ", "て"], target: {symbol: "て", sound: "te"}},
    {level: 20, numberOfCards: 100, symbols: ["た", "と", "ち", "と", "つ", "て", "と"], target: {symbol: "と", sound: "to"}},
    {level: 21, numberOfCards: 100, symbols: ["な", "に", "ぬ", "な", "ね", "の", "な"], target: {symbol: "な", sound: "na"}},
    {level: 22, numberOfCards: 100, symbols: ["な", "に", "ぬ", "に", "ね", "の", "に"], target: {symbol: "に", sound: "ni"}},
    {level: 23, numberOfCards: 100, symbols: ["な", "ぬ", "に", "ぬ", "ね", "の", "ぬ"], target: {symbol: "ぬ", sound: "nu"}},
    {level: 24, numberOfCards: 100, symbols: ["な", "ね", "に", "ぬ", "ね", "の", "ね"], target: {symbol: "ね", sound: "ne"}},
    {level: 25, numberOfCards: 100, symbols: ["な", "の", "に", "の", "ぬ", "ね", "の"], target: {symbol: "の", sound: "no"}},
    {level: 26, numberOfCards: 100, symbols: ["は", "ひ", "ふ", "は", "へ", "ほ", "は"], target: {symbol: "は", sound: "ha"}},
    {level: 27, numberOfCards: 100, symbols: ["は", "ひ", "ふ", "ひ", "へ", "ほ", "ひ"], target: {symbol: "ひ", sound: "hi"}},
    {level: 28, numberOfCards: 100, symbols: ["は", "ふ", "ひ", "ふ", "へ", "ほ", "ふ"], target: {symbol: "ふ", sound: "fu"}},
    {level: 29, numberOfCards: 100, symbols: ["は", "へ", "ひ", "ふ", "へ", "ほ", "へ"], target: {symbol: "へ", sound: "he"}},
    {level: 30, numberOfCards: 100, symbols: ["は", "ほ", "ひ", "ほ", "ふ", "へ", "ほ"], target: {symbol: "ほ", sound: "ho"}},
    {level: 31, numberOfCards: 100, symbols: ["ま", "み", "む", "ま", "め", "も", "ま"], target: {symbol: "ま", sound: "ma"}},
    {level: 32, numberOfCards: 100, symbols: ["ま", "み", "む", "み", "め", "も", "み"], target: {symbol: "み", sound: "mi"}},
    {level: 33, numberOfCards: 100, symbols: ["ま", "む", "み", "む", "め", "も", "む"], target: {symbol: "む", sound: "mu"}},
    {level: 34, numberOfCards: 100, symbols: ["ま", "め", "み", "む", "め", "も", "め"], target: {symbol: "め", sound: "me"}},
    {level: 35, numberOfCards: 100, symbols: ["ま", "も", "み", "も", "む", "め", "も"], target: {symbol: "も", sound: "mo"}},
    {level: 36, numberOfCards: 100, symbols: ["ら", "り", "ら", "る", "れ", "ろ", "ら"], target: {symbol: "ら", sound: "ra"}},
    {level: 37, numberOfCards: 100, symbols: ["ら", "り", "る", "り", "れ", "ろ", "り"], target: {symbol: "り", sound: "ri"}},
    {level: 38, numberOfCards: 100, symbols: ["ら", "る", "り", "る", "れ", "ろ", "る"], target: {symbol: "る", sound: "ru"}},
    {level: 39, numberOfCards: 100, symbols: ["ら", "れ", "り", "る", "れ", "ろ", "れ"], target: {symbol: "れ", sound: "re"}},
    {level: 40, numberOfCards: 100, symbols: ["ら", "ろ", "り", "ろ", "る", "れ", "ろ"], target: {symbol: "ろ", sound: "ro"}},
    

    


]